const kanjiData = [
  { kanji: "理解", hiragana: "りかい", arti: "pemahaman" },
  { kanji: "制度", hiragana: "せいど", arti: "sistem" },
  { kanji: "供給", hiragana: "きょうきゅう", arti: "pasokan" },
  { kanji: "促進", hiragana: "そくしん", arti: "mendorong, memajukan" },
  { kanji: "推進", hiragana: "すいしん", arti: "memajukan, mendorong" },
  { kanji: "財政", hiragana: "ざいせい", arti: "keuangan negara" },
  { kanji: "納税", hiragana: "のうぜい", arti: "pembayaran pajak" },
  { kanji: "貯蓄", hiragana: "ちょちく", arti: "tabungan" },
  { kanji: "利息", hiragana: "りそく", arti: "bunga" },
  { kanji: "製造", hiragana: "せいぞう", arti: "produksi" },

  { kanji: "製品", hiragana: "せいひん", arti: "produk" },
  { kanji: "生産", hiragana: "せいさん", arti: "produksi" },
  { kanji: "消費", hiragana: "しょうひ", arti: "konsumsi" },
  { kanji: "輸出", hiragana: "ゆしゅつ", arti: "ekspor" },
  { kanji: "輸入", hiragana: "ゆにゅう", arti: "impor" },
  { kanji: "経済", hiragana: "けいざい", arti: "ekonomi" },
  { kanji: "経営", hiragana: "けいえい", arti: "manajemen, pengelolaan" },
  { kanji: "企業", hiragana: "きぎょう", arti: "perusahaan" },
  { kanji: "産業", hiragana: "さんぎょう", arti: "industri" },
  { kanji: "農業", hiragana: "のうぎょう", arti: "pertanian" },

  { kanji: "政治", hiragana: "せいじ", arti: "politik" },
  { kanji: "政府", hiragana: "せいふ", arti: "pemerintah" },
  { kanji: "国会", hiragana: "こっかい", arti: "parlemen" },
  { kanji: "法律", hiragana: "ほうりつ", arti: "hukum" },
  { kanji: "条約", hiragana: "じょうやく", arti: "perjanjian" },
  { kanji: "制度", hiragana: "せいど", arti: "sistem, lembaga" },
  { kanji: "義務", hiragana: "ぎむ", arti: "kewajiban" },
  { kanji: "権利", hiragana: "けんり", arti: "hak" },
  { kanji: "責任", hiragana: "せきにん", arti: "tanggung jawab" },
  { kanji: "国民", hiragana: "こくみん", arti: "rakyat, warga negara" },

  { kanji: "支配", hiragana: "しはい", arti: "penguasaan" },
  { kanji: "植民地", hiragana: "しょくみんち", arti: "koloni" },
  { kanji: "革命", hiragana: "かくめい", arti: "revolusi" },
  { kanji: "統一", hiragana: "とういつ", arti: "penyatuan" },
  { kanji: "独立", hiragana: "どくりつ", arti: "kemerdekaan, independen" },
  { kanji: "国家", hiragana: "こっか", arti: "negara" },
  { kanji: "国際", hiragana: "こくさい", arti: "internasional" },
  { kanji: "外交", hiragana: "がいこう", arti: "diplomasi" },
  { kanji: "裁判", hiragana: "さいばん", arti: "persidangan" },
  { kanji: "証言", hiragana: "しょうげん", arti: "kesaksian" },

  { kanji: "環境", hiragana: "かんきょう", arti: "lingkungan" },
  { kanji: "自然", hiragana: "しぜん", arti: "alam" },
  { kanji: "自然破壊", hiragana: "しぜんはかい", arti: "kerusakan alam" },
  { kanji: "資源", hiragana: "しげん", arti: "sumber daya" },
  { kanji: "再生", hiragana: "さいせい", arti: "daur ulang, pemulihan" },
  { kanji: "温暖化", hiragana: "おんだんか", arti: "pemanasan global" },
  { kanji: "汚染", hiragana: "おせん", arti: "pencemaran" },
  { kanji: "保護", hiragana: "ほご", arti: "perlindungan" },
  { kanji: "防止", hiragana: "ぼうし", arti: "pencegahan" },
  { kanji: "対策", hiragana: "たいさく", arti: "langkah penanganan" },

  { kanji: "問題", hiragana: "もんだい", arti: "masalah" },
  { kanji: "課題", hiragana: "かだい", arti: "tugas, masalah yang harus ditangani" },
  { kanji: "解決", hiragana: "かいけつ", arti: "penyelesaian" },
  { kanji: "原因", hiragana: "げんいん", arti: "penyebab" },
  { kanji: "結果", hiragana: "けっか", arti: "hasil" },
  { kanji: "影響", hiragana: "えいきょう", arti: "pengaruh, dampak" },
  { kanji: "効果", hiragana: "こうか", arti: "efek" },
  { kanji: "目的", hiragana: "もくてき", arti: "tujuan" },
  { kanji: "方法", hiragana: "ほうほう", arti: "cara, metode" },
  { kanji: "必要", hiragana: "ひつよう", arti: "perlu, kebutuhan" },

  { kanji: "確認", hiragana: "かくにん", arti: "memastikan, konfirmasi" },
  { kanji: "判断", hiragana: "はんだん", arti: "penilaian, keputusan" },
  { kanji: "決定", hiragana: "けってい", arti: "keputusan, penetapan" },
  { kanji: "選択", hiragana: "せんたく", arti: "pilihan" },
  { kanji: "判断", hiragana: "はんだん", arti: "penilaian" },
  { kanji: "説明", hiragana: "せつめい", arti: "penjelasan" },
  { kanji: "証明", hiragana: "しょうめい", arti: "pembuktian" },
  { kanji: "調査", hiragana: "ちょうさ", arti: "penyelidikan, survei" },
  { kanji: "研究", hiragana: "けんきゅう", arti: "penelitian" },
  { kanji: "分析", hiragana: "ぶんせき", arti: "analisis" },

  { kanji: "増加", hiragana: "ぞうか", arti: "peningkatan" },
  { kanji: "減少", hiragana: "げんしょう", arti: "penurunan" },
  { kanji: "変化", hiragana: "へんか", arti: "perubahan" },
  { kanji: "発展", hiragana: "はってん", arti: "perkembangan" },
  { kanji: "成長", hiragana: "せいちょう", arti: "pertumbuhan" },
  { kanji: "発生", hiragana: "はっせい", arti: "terjadi, timbul" },
  { kanji: "発見", hiragana: "はっけん", arti: "penemuan" },
  { kanji: "発表", hiragana: "はっぴょう", arti: "pengumuman, presentasi" },
  { kanji: "実現", hiragana: "じつげん", arti: "mewujudkan" },
  { kanji: "実施", hiragana: "じっし", arti: "pelaksanaan" },

  { kanji: "提供", hiragana: "ていきょう", arti: "menyediakan" },
  { kanji: "利用", hiragana: "りよう", arti: "penggunaan" },
  { kanji: "活用", hiragana: "かつよう", arti: "pemanfaatan" },
  { kanji: "対応", hiragana: "たいおう", arti: "menangani, merespons" },
  { kanji: "処理", hiragana: "しょり", arti: "memproses, penanganan" },
  { kanji: "管理", hiragana: "かんり", arti: "pengelolaan" },
  { kanji: "維持", hiragana: "いじ", arti: "mempertahankan" },
  { kanji: "改善", hiragana: "かいぜん", arti: "perbaikan" },
  { kanji: "努力", hiragana: "どりょく", arti: "usaha" },
  { kanji: "達成", hiragana: "たっせい", arti: "pencapaian" },

  { kanji: "状況", hiragana: "じょうきょう", arti: "situasi, keadaan" },
  { kanji: "状態", hiragana: "じょうたい", arti: "kondisi, keadaan" },
  { kanji: "現状", hiragana: "げんじょう", arti: "keadaan saat ini" },
  { kanji: "傾向", hiragana: "けいこう", arti: "kecenderungan" },
  { kanji: "特徴", hiragana: "とくちょう", arti: "ciri khas" },
  { kanji: "原因", hiragana: "げんいん", arti: "penyebab" },
  { kanji: "価値", hiragana: "かち", arti: "nilai" },
  { kanji: "意識", hiragana: "いしき", arti: "kesadaran" },
  { kanji: "知識", hiragana: "ちしき", arti: "pengetahuan" },
  { kanji: "経験", hiragana: "けいけん", arti: "pengalaman" }
];
