const kanjiData = [
  { kanji: "理解", hiragana: "りかい", arti: "pemahaman" },
  { kanji: "制度", hiragana: "せいど", arti: "sistem" },
  { kanji: "供給", hiragana: "きょうきゅう", arti: "pasokan" },
  { kanji: "促進", hiragana: "そくしん", arti: "mendorong, memajukan" },
  { kanji: "推進", hiragana: "すいしん", arti: "memajukan, mendorong" },
  { kanji: "財政", hiragana: "ざいせい", arti: "keuangan negara" },
  { kanji: "納税", hiragana: "のうぜい", arti: "pembayaran pajak" },
  { kanji: "貯蓄", hiragana: "ちょちく", arti: "tabungan" },
  { kanji: "利息", hiragana: "りそく", arti: "bunga" },
  { kanji: "製造", hiragana: "せいぞう", arti: "produksi" },

  { kanji: "製品", hiragana: "せいひん", arti: "produk" },
  { kanji: "生産", hiragana: "せいさん", arti: "produksi" },
  { kanji: "消費", hiragana: "しょうひ", arti: "konsumsi" },
  { kanji: "輸出", hiragana: "ゆしゅつ", arti: "ekspor" },
  { kanji: "輸入", hiragana: "ゆにゅう", arti: "impor" },
  { kanji: "経済", hiragana: "けいざい", arti: "ekonomi" },
  { kanji: "経営", hiragana: "けいえい", arti: "manajemen, pengelolaan" },
  { kanji: "企業", hiragana: "きぎょう", arti: "perusahaan" },
  { kanji: "産業", hiragana: "さんぎょう", arti: "industri" },
  { kanji: "農業", hiragana: "のうぎょう", arti: "pertanian" },

  { kanji: "政治", hiragana: "せいじ", arti: "politik" },
  { kanji: "政府", hiragana: "せいふ", arti: "pemerintah" },
  { kanji: "国会", hiragana: "こっかい", arti: "parlemen" },
  { kanji: "法律", hiragana: "ほうりつ", arti: "hukum" },
  { kanji: "条約", hiragana: "じょうやく", arti: "perjanjian" },
  { kanji: "制度", hiragana: "せいど", arti: "sistem, lembaga" },
  { kanji: "義務", hiragana: "ぎむ", arti: "kewajiban" },
  { kanji: "権利", hiragana: "けんり", arti: "hak" },
  { kanji: "責任", hiragana: "せきにん", arti: "tanggung jawab" },
  { kanji: "国民", hiragana: "こくみん", arti: "rakyat, warga negara" },

  { kanji: "支配", hiragana: "しはい", arti: "penguasaan" },
  { kanji: "植民地", hiragana: "しょくみんち", arti: "koloni" },
  { kanji: "革命", hiragana: "かくめい", arti: "revolusi" },
  { kanji: "統一", hiragana: "とういつ", arti: "penyatuan" },
  { kanji: "独立", hiragana: "どくりつ", arti: "kemerdekaan, independen" },
  { kanji: "国家", hiragana: "こっか", arti: "negara" },
  { kanji: "国際", hiragana: "こくさい", arti: "internasional" },
  { kanji: "外交", hiragana: "がいこう", arti: "diplomasi" },
  { kanji: "裁判", hiragana: "さいばん", arti: "persidangan" },
  { kanji: "証言", hiragana: "しょうげん", arti: "kesaksian" },

  { kanji: "環境", hiragana: "かんきょう", arti: "lingkungan" },
  { kanji: "自然", hiragana: "しぜん", arti: "alam" },
  { kanji: "自然破壊", hiragana: "しぜんはかい", arti: "kerusakan alam" },
  { kanji: "資源", hiragana: "しげん", arti: "sumber daya" },
  { kanji: "再生", hiragana: "さいせい", arti: "daur ulang, pemulihan" },
  { kanji: "温暖化", hiragana: "おんだんか", arti: "pemanasan global" },
  { kanji: "汚染", hiragana: "おせん", arti: "pencemaran" },
  { kanji: "保護", hiragana: "ほご", arti: "perlindungan" },
  { kanji: "防止", hiragana: "ぼうし", arti: "pencegahan" },
  { kanji: "対策", hiragana: "たいさく", arti: "langkah penanganan" },

  { kanji: "問題", hiragana: "もんだい", arti: "masalah" },
  { kanji: "課題", hiragana: "かだい", arti: "tugas, masalah yang harus ditangani" },
  { kanji: "解決", hiragana: "かいけつ", arti: "penyelesaian" },
  { kanji: "原因", hiragana: "げんいん", arti: "penyebab" },
  { kanji: "結果", hiragana: "けっか", arti: "hasil" },
  { kanji: "影響", hiragana: "えいきょう", arti: "pengaruh, dampak" },
  { kanji: "効果", hiragana: "こうか", arti: "efek" },
  { kanji: "目的", hiragana: "もくてき", arti: "tujuan" },
  { kanji: "方法", hiragana: "ほうほう", arti: "cara, metode" },
  { kanji: "必要", hiragana: "ひつよう", arti: "perlu, kebutuhan" },

  { kanji: "確認", hiragana: "かくにん", arti: "memastikan, konfirmasi" },
  { kanji: "判断", hiragana: "はんだん", arti: "penilaian, keputusan" },
  { kanji: "決定", hiragana: "けってい", arti: "keputusan, penetapan" },
  { kanji: "選択", hiragana: "せんたく", arti: "pilihan" },
  { kanji: "判断", hiragana: "はんだん", arti: "penilaian" },
  { kanji: "説明", hiragana: "せつめい", arti: "penjelasan" },
  { kanji: "証明", hiragana: "しょうめい", arti: "pembuktian" },
  { kanji: "調査", hiragana: "ちょうさ", arti: "penyelidikan, survei" },
  { kanji: "研究", hiragana: "けんきゅう", arti: "penelitian" },
  { kanji: "分析", hiragana: "ぶんせき", arti: "analisis" },

  { kanji: "増加", hiragana: "ぞうか", arti: "peningkatan" },
  { kanji: "減少", hiragana: "げんしょう", arti: "penurunan" },
  { kanji: "変化", hiragana: "へんか", arti: "perubahan" },
  { kanji: "発展", hiragana: "はってん", arti: "perkembangan" },
  { kanji: "成長", hiragana: "せいちょう", arti: "pertumbuhan" },
  { kanji: "発生", hiragana: "はっせい", arti: "terjadi, timbul" },
  { kanji: "発見", hiragana: "はっけん", arti: "penemuan" },
  { kanji: "発表", hiragana: "はっぴょう", arti: "pengumuman, presentasi" },
  { kanji: "実現", hiragana: "じつげん", arti: "mewujudkan" },
  { kanji: "実施", hiragana: "じっし", arti: "pelaksanaan" },

  { kanji: "提供", hiragana: "ていきょう", arti: "menyediakan" },
  { kanji: "利用", hiragana: "りよう", arti: "penggunaan" },
  { kanji: "活用", hiragana: "かつよう", arti: "pemanfaatan" },
  { kanji: "対応", hiragana: "たいおう", arti: "menangani, merespons" },
  { kanji: "処理", hiragana: "しょり", arti: "memproses, penanganan" },
  { kanji: "管理", hiragana: "かんり", arti: "pengelolaan" },
  { kanji: "維持", hiragana: "いじ", arti: "mempertahankan" },
  { kanji: "改善", hiragana: "かいぜん", arti: "perbaikan" },
  { kanji: "努力", hiragana: "どりょく", arti: "usaha" },
  { kanji: "達成", hiragana: "たっせい", arti: "pencapaian" },

  { kanji: "状況", hiragana: "じょうきょう", arti: "situasi, keadaan" },
  { kanji: "状態", hiragana: "じょうたい", arti: "kondisi, keadaan" },
  { kanji: "現状", hiragana: "げんじょう", arti: "keadaan saat ini" },
  { kanji: "傾向", hiragana: "けいこう", arti: "kecenderungan" },
  { kanji: "特徴", hiragana: "とくちょう", arti: "ciri khas" },
  { kanji: "原因", hiragana: "げんいん", arti: "penyebab" },
  { kanji: "価値", hiragana: "かち", arti: "nilai" },
  { kanji: "意識", hiragana: "いしき", arti: "kesadaran" },
  { kanji: "知識", hiragana: "ちしき", arti: "pengetahuan" },
  { kanji: "経験", hiragana: "けいけん", arti: "pengalaman" }
    { kanji: "実際", hiragana: "じっさい", arti: "kenyataannya, sebenarnya" },
  { kanji: "具体的", hiragana: "ぐたいてき", arti: "konkret, spesifik" },
  { kanji: "基本的", hiragana: "きほんてき", arti: "mendasar, fundamental" },
  { kanji: "一般的", hiragana: "いっぱんてき", arti: "umum" },
  { kanji: "積極的", hiragana: "せっきょくてき", arti: "aktif, positif" },
  { kanji: "消極的", hiragana: "しょうきょくてき", arti: "pasif, negatif" },
  { kanji: "客観的", hiragana: "きゃっかんてき", arti: "objektif" },
  { kanji: "主観的", hiragana: "しゅかんてき", arti: "subjektif" },
  { kanji: "合理的", hiragana: "ごうりてき", arti: "rasional" },
  { kanji: "効果的", hiragana: "こうかてき", arti: "efektif" },

  { kanji: "急激", hiragana: "きゅうげき", arti: "drastis, mendadak" },
  { kanji: "急速", hiragana: "きゅうそく", arti: "cepat, pesat" },
  { kanji: "大幅", hiragana: "おおはば", arti: "besar, signifikan" },
  { kanji: "微妙", hiragana: "びみょう", arti: "sulit dikatakan, samar" },
  { kanji: "明確", hiragana: "めいかく", arti: "jelas" },
  { kanji: "適切", hiragana: "てきせつ", arti: "tepat, sesuai" },
  { kanji: "適当", hiragana: "てきとう", arti: "sesuai, tepat" },
  { kanji: "重大", hiragana: "じゅうだい", arti: "serius, penting" },
  { kanji: "重要", hiragana: "じゅうよう", arti: "penting" },
  { kanji: "豊富", hiragana: "ほうふ", arti: "melimpah, kaya" },

  { kanji: "不足", hiragana: "ふそく", arti: "kekurangan" },
  { kanji: "余裕", hiragana: "よゆう", arti: "kelonggaran,余裕" },
  { kanji: "余分", hiragana: "よぶん", arti: "kelebihan, tambahan" },
  { kanji: "巨大", hiragana: "きょだい", arti: "sangat besar" },
  { kanji: "膨大", hiragana: "ぼうだい", arti: "sangat banyak" },
  { kanji: "莫大", hiragana: "ばくだい", arti: "sangat besar, sangat banyak" },
  { kanji: "複雑", hiragana: "ふくざつ", arti: "rumit" },
  { kanji: "単純", hiragana: "たんじゅん", arti: "sederhana" },
  { kanji: "特殊", hiragana: "とくしゅ", arti: "khusus, unik" },
  { kanji: "一般", hiragana: "いっぱん", arti: "umum" },

  { kanji: "通常", hiragana: "つうじょう", arti: "biasanya, normal" },
  { kanji: "正式", hiragana: "せいしき", arti: "resmi" },
  { kanji: "独自", hiragana: "どくじ", arti: "unik, sendiri" },
  { kanji: "共通", hiragana: "きょうつう", arti: "umum, sama" },
  { kanji: "公平", hiragana: "こうへい", arti: "adil" },
  { kanji: "平等", hiragana: "びょうどう", arti: "kesetaraan" },
  { kanji: "有効", hiragana: "ゆうこう", arti: "berlaku, efektif" },
  { kanji: "無効", hiragana: "むこう", arti: "tidak berlaku" },
  { kanji: "有利", hiragana: "ゆうり", arti: "menguntungkan" },
  { kanji: "不利", hiragana: "ふり", arti: "merugikan" },

  { kanji: "可能", hiragana: "かのう", arti: "mungkin" },
  { kanji: "不可能", hiragana: "ふかのう", arti: "tidak mungkin" },
  { kanji: "困難", hiragana: "こんなん", arti: "kesulitan" },
  { kanji: "容易", hiragana: "ようい", arti: "mudah" },
  { kanji: "危険", hiragana: "きけん", arti: "bahaya" },
  { kanji: "安全", hiragana: "あんぜん", arti: "aman" },
  { kanji: "必要性", hiragana: "ひつようせい", arti: "kebutuhan, pentingnya" },
  { kanji: "可能性", hiragana: "かのうせい", arti: "kemungkinan" },
  { kanji: "必要性", hiragana: "ひつようせい", arti: "kebutuhan" },
  { kanji: "重要性", hiragana: "じゅうようせい", arti: "pentingnya" },

  { kanji: "傾向", hiragana: "けいこう", arti: "kecenderungan" },
  { kanji: "方向", hiragana: "ほうこう", arti: "arah" },
  { kanji: "方針", hiragana: "ほうしん", arti: "kebijakan, arah" },
  { kanji: "方策", hiragana: "ほうさく", arti: "strategi, langkah" },
  { kanji: "手段", hiragana: "しゅだん", arti: "cara, sarana" },
  { kanji: "手続き", hiragana: "てつづき", arti: "prosedur" },
  { kanji: "手順", hiragana: "てじゅん", arti: "urutan langkah" },
  { kanji: "手間", hiragana: "てま", arti: "waktu/tenaga yang diperlukan" },
  { kanji: "手掛かり", hiragana: "てがかり", arti: "petunjuk" },
  { kanji: "手本", hiragana: "てほん", arti: "contoh, teladan" },

  { kanji: "原因", hiragana: "げんいん", arti: "penyebab" },
  { kanji: "要因", hiragana: "よういん", arti: "faktor penyebab" },
  { kanji: "要素", hiragana: "ようそ", arti: "unsur, elemen" },
  { kanji: "条件", hiragana: "じょうけん", arti: "syarat, kondisi" },
  { kanji: "前提", hiragana: "ぜんてい", arti: "prasyarat, asumsi" },
  { kanji: "基準", hiragana: "きじゅん", arti: "standar, kriteria" },
  { kanji: "基礎", hiragana: "きそ", arti: "dasar" },
  { kanji: "基盤", hiragana: "きばん", arti: "fondasi, dasar" },
  { kanji: "根拠", hiragana: "こんきょ", arti: "dasar, bukti" },
  { kanji: "証拠", hiragana: "しょうこ", arti: "bukti" },

  { kanji: "意見", hiragana: "いけん", arti: "pendapat" },
  { kanji: "主張", hiragana: "しゅちょう", arti: "pendapat, klaim" },
  { kanji: "提案", hiragana: "ていあん", arti: "usulan" },
  { kanji: "要求", hiragana: "ようきゅう", arti: "tuntutan, permintaan" },
  { kanji: "希望", hiragana: "きぼう", arti: "harapan" },
  { kanji: "期待", hiragana: "きたい", arti: "harapan, ekspektasi" },
  { kanji: "賛成", hiragana: "さんせい", arti: "setuju" },
  { kanji: "反対", hiragana: "はんたい", arti: "menentang, berlawanan" },
  { kanji: "批判", hiragana: "ひはん", arti: "kritik" },
  { kan
];
